### PR TITLE
Use H5P.Timer library

### PR DESCRIPTION
**Pull request by otacke**
I propose this pull request in order to show how my library H5P.Timer could be used if it was integrated into the official release of H5P. Accordingly, [v0.3 of H5P.Timer needs to be present](https://github.com/otacke/h5p-timer/releases/tag/v0.3-alpha) at well.

The H5P.Timer is a general purpose timer that could be used by other H5P libraries. It is not intended for time critical applications, but it can easily be used to keep track of time in games, to set a time limit for tasks, or to create other innovative content libraries that need triggers based on time. What about a mod-player that can handle ProTracker files for example? ;-)

Although I tested the library, there still might be some bugs. But they're free!
## Features
- can count up and down
- can use milliseconds internally but only "displays" tenths of seconds and above
- can be paused
- keeps track of three different types of counters
  - clock time (can be modified even if running, e.g to give a time bonus)
  - playing time (the amount of time that the clock has been ticking)
  - running time (the total running time ignoring pauses)
- offers three types of notifications using callback functions for each type of counter
  - notification at a particular point in time
  - notification after a certain time period has passed
  - recurring notifications in fixed intervals
- dispatches events for play, pause, stop and reset
- offers some static utility functions
  - check if something is a timecode
  - convert timecodes to milliseconds and vice versa
  - extract single time elements like days or seconds from timecode or milliseconds

Please [visit the H5P-Timer wiki](https://github.com/otacke/h5p-timer/wiki) for information on how to use the library.

### CODE REVIEW

**Comment by icc** [comment]
I think the code looks good. I will do some more testing before merging in, but I don't see any obvious issues with it.

Regarding release, I think it's easiest if I push your repo to /h5p/h5p-timer and then just grant you access to it.

**Comment by icc** [comment]
One think about the interface; it would be cool if it was a bit cleaner and easier to read. For example something like this:
```
timer.on('everySecond', function () {...})
```
or something like that. Perhaps [Promise](promisejs.org) syntax?

**Comment by otacke** [comment]
Sure! I'll have a look at PromiseJS and see what I can do. Learning something new every day... :-)

**Comment by otacke** [comment]
Alright, I think I now have a basic understanding of the concept of promises. I could ditch the callback function and its parameters, making the code easier to follow. I could also create some "common" static parameter objects like 'everySecond' on the clock counter, making it even easier - although I would not want to forfeit flexibility and still keep the other variables as an option (three different counters, defining when to start, defining the interval, three different options for triggering (at, in and every)).

But, here comes the but. Right now, my notification functions return an ID that can be used to stop them if necessary. How would I implement that feature best with promises? You could probably simply ignore them, but they would still be running in h5p-timer even if they have become obsolete. I guess, deleting the promise object won't be enough, right?

Also, I am not sure yet what the best way would be for changing the triggering mechanism with promises, but at least I have a rough idea for that.

Sorry if I am misusing this comments section for my own learning process. Just tell my if I should rather use StackOverflow or something similar.

**Comment by otacke** [comment]
Oooouh. Doh! Re-reading your post: Did you in fact mean using promises or just a similar (simplified) syntax for notification calls?

**Comment by icc** [comment]
Ah yes, I was only talking about the syntax, apologies for not being clearer on that! I don't think it hurts that you've had a go at promises, I think that they will be come quite more important in the JavaScript world in a not too distant future.

Yes, the timer is quite flexible – my concern is if it will be easy enough for others to start using it as well. It can look a bit complex and scary at first eyesight, that is all.

Well I at least,  think that it's best to have the comments, discussions and learning process as close to the code as possible :-)

**Comment by otacke** [comment]
I absolutely don't mind having learned about promises, and your suggestion was clear - just should have read it more diligently.

I can think of several solutions, and my favorite one would be to have just two parameters as in your example. The latter one would be the function to be executed, given directly, the previous one either a String representing some predefined defaults such as 'every second' or an object containing settings in more detail. The one thing I wonder: is it good practice to use two different types for a parameter?

**Comment by icc** [comment]
Yup, that would probably be ideal for novice users. I think it's quite common, at least in JavaScript, to support both a simple string or a more advanced object of properties as a parameter.

**Comment by otacke** [comment]
Great, thanks! I'll change my code then.

**Comment by otacke** [comment]
I changed H5P-Timer according to your suggestions. [It now bears version number v4.0-alpha](https://github.com/otacke/h5p-timer/releases/tag/v0.4-alpha). Thanks!

**Comment by icc** [comment]
Works great, thank you!

(note that I bumped the version requirement to 0.4 in library.json)

**Pull request merged**
