### PR TITLE
Create nl.json

### PR DESCRIPTION
**Pull request by ReneBreedveld**
Add Dutch translation

### CODE REVIEW

**Comment by timothyylim** [comment]
Hi @ReneBreedveld, we are trying out a translation service called Crowdin which will hopefully make it easier for community members to submit translations. Would you be able to add these translations via the project page on crowdin?

https://crowdin.com/project/h5p-memory-game/settings#translations

You can just log in using your github account.

Let me know how it goes :)

**Comment by ReneBreedveld** [comment]
Hi @timothyylim 
Thank you for your reply. 

I've tried to make use of the above-mentioned service Crowdin. Unfortunately, I couldn't log in with my Github account as proposed.

**Comment by timothyylim** [comment]
@ReneBreedveld , perhaps you may have to create a new account.

**Comment by ReneBreedveld** [comment]
I've just made a Crowdin login. So, please let me know what's next to do. Besides this I shall collaborate with another Dutch translator in order to be ready before the H5P presentation in The Netherlands on 24th May.

**Comment by timothyylim** [comment]
Great, could you try the following link:

https://crowdin.com/project/h5p-memory-game/settings#translations

**Comment by ReneBreedveld** [comment]
Yes I did. 

Result - Something went wrong.
Project does not exist or access to this project is limited. In case you are confident that you have access to the project, try to switch account if you have several or contact project manager for further assistance.

**Comment by timothyylim** [comment]
Very strange. Would you be able to share your crowdin login and I can try a manual invite.

**Comment by ReneBreedveld** [comment]
Sorry, I don't know exactly what you mean by sharing my Crowdin login. What do I have to do?

**Comment by timothyylim** [comment]
I meant the username you use to login into Crowdin :)
If you can share that here, I can send you a direct invite to upload your translations.

**Comment by ReneBreedveld** [comment]
Thank you for your reply. My username is rbreedveld@casema.nl

**Comment by timothyylim** [comment]
An invite has been sent to your email 👍

**Comment by ReneBreedveld** [comment]
Thank you for the invitation. 
I've already executed the Dutch translation as you can see in Crowdin and I support your assumption for easier translation opportunities. Can I contribute to other projects as well?

**Comment by timothyylim** [comment]
@ReneBreedveld , great job with adding the Dutch translations via Crowdin, I see you've already gone ahead and translated some other content types too :) I'll close this pull request and merge your translation on the localization l10n branch. 

I'm slowly adding the content types one by one just to make sure that there aren't any problems. I'll keep you posted when I make some progress.

**Pull request closed without merging**
